Description of CacheClassSwitcher
Home > src > lang > CacheClassSwitcher.m
CacheClassSwitcher
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
CacheClassSwitcher
StatefulClassSwitcher
This function is called by:
Cache
CacheClassSwitcher
SUBFUNCTIONS
function self = CacheClassSwitcher(classes, items, capacity, levels)
function prob = simpleHitMiss(self, r, s, state, statep)
SOURCE CODE
classdef CacheClassSwitcher < StatefulClassSwitcher
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        items;
        cap;
        levels;
        inputJobClasses;
        hitClass;
        missClass;
    end
    methods
        function self = CacheClassSwitcher(classes, items, capacity, levels)
            if ~exist('levels','var')
                levels = 1;
            end
            self = self@StatefulClassSwitcher(classes, 'Cache');
            self.classes = classes;
            self.items = items;
            self.cap = capacity;
            self.levels = levels;
            self.csFun = @(r, s, state, statep) self.simpleHitMiss(r, s, state, statep); % do nothing by default
            self.hitClass = sparse([]);
            self.missClass = sparse([]);
        end
    end
    methods
        function prob = simpleHitMiss(self, r, s, state, statep)
            if nargin <= 3
                state = []; %local server state
                statep = []; %local server state
            end
            if isempty(state) % get csMask
                if (r==s  ... % hit and miss in the cache can depart in the same class
                    || ((r <= length(self.hitClass) && r <= length(self.missClass)) ... % since hitClass and missClass are sparse, check entry for r exists
                        && (s == self.hitClass(r) || s == self.missClass(r)))) ... % route out hit or miss classes
                        && (~isempty(find(r == self.hitClass)) || ~isempty(find(r == self.missClass))) % don't route out classes that are not hit or miss
                    prob = 1;
                else
                    prob = 0;
                end
            else
                 % un-comment to restore class-switching in routing
%                 if sum(state) == sum(statep)+1 % hit
%                     if (r <= length(self.hitClass)) && s == self.hitClass(r)
%                         prob = 1;
%                     else
%                         prob = 0;
%                     end
%                 else % miss
%                     if (r <= length(self.missClass)) && s == self.missClass(r)
%                         prob = 1;
%                     else
%                         prob = 0;
%                     end
%                 end
            end
        end
    end
end