Description of Dispatcher
Home > src > lang > Dispatcher.m
Dispatcher
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Dispatcher
OutputSection
This function is called by:
Cache
ClassSwitch
Dispatcher
Join
Logger
Queue
Router
Source
SUBFUNCTIONS
function self = Dispatcher(customerClasses)
function initDispatcherJobClasses(self, customerClasses)
function setStrategy(self, customerClasses, strategy)
SOURCE CODE
classdef Dispatcher < OutputSection
    % Copyright (c) 2012-2019, Imperial College London
    % All rights reserved.
    methods
        %Constructor
        function self = Dispatcher(customerClasses)
            self = self@OutputSection('Dispatcher');
            self.outputStrategy = {};
            initDispatcherJobClasses(self, customerClasses);
     end
    end
    methods
        function initDispatcherJobClasses(self, customerClasses)
            for r = 1 : length(customerClasses)
                self.outputStrategy{r} = {customerClasses{r}.name, RoutingStrategy.ID_RAND};
            end
        end
        function setStrategy(self, customerClasses, strategy)
            if length(strategy) == 1
                self.outputStrategy{customerClasses{r}.index} = {customerClasses{r}.name, strategy};
            else
                for r = 1 : length(customerClasses)
                    self.outputStrategy{customerClasses{r}.index} = {customerClasses{r}.name, strategy{r}};
                end
            end
        end
    end
end