Description of Forker
Home > src > lang > Forker.m
Forker
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Forker
OutputSection
This function is called by:
Fork
Forker
SUBFUNCTIONS
function self = Forker(customerClasses)
function initDispatcherJobClasses(self, customerClasses)
function clone = copyElement(self)
SOURCE CODE
classdef Forker < OutputSection
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        tasksPerLink;
    end
    methods
        %Constructor
        function self = Forker(customerClasses)
            self = self@OutputSection('Forker');
            self.tasksPerLink=1.0;
            initDispatcherJobClasses(self, customerClasses);
        end
    end
    methods (Access = 'private')
        function initDispatcherJobClasses(self, customerClasses)
           for i = 1 : length(customerClasses)
              self.outputStrategy{i} = {customerClasses{i}.name, RoutingStrategy.RAND};
           end
        end
    end
       methods(Access = protected)
        % Override copyElement method:
        function clone = copyElement(self)
            % Make a shallow copy of all properties
            clone = copyElement@Copyable(self);
            % Make a deep copy of each object
            for i = 1 : length(self.outputStrategy)
                if ishandle(clone.outputStrategy{i}{1})
                    % this is a problem if one modifies the classes in the
                    % model because the one below is not an handle so it
                    % will not be modified
                    clone.outputStrategy{i}{1} = self.outputStrategy{i}{1}.copy;
                end
            end
        end
    end
end