Description of Fork
Home > src > lang > Fork.m
Fork
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Buffer
Fork
Forker
Node
ServiceTunnel
This function is called by:
Fork
NodeType
SUBFUNCTIONS
function self = Fork(model, name)
function setTasksPerLink(self, nTasks)
SOURCE CODE
classdef Fork < Node
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        schedStrategy;
        cap;
    end
    methods
        %Constructor
        function self = Fork(model, name)
            self = self@Node(name);
            if(model ~= 0)
                classes = model.classes;
                self.cap = Inf;
                self.input = Buffer(classes);
                self.schedStrategy = SchedStrategy.FORK;
                self.server = ServiceTunnel();
                self.output = Forker(classes);
                self.setModel(model);
                addNode(model, self);
            end
        end
        function setTasksPerLink(self, nTasks)
            self.output.tasksPerLink = nTasks;
        end
    end
end