Description of InputSection
Home > src > lang > InputSection.m
InputSection
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
InputSection
Section
This function is called by:
Buffer
InputSection
RandomSource
SUBFUNCTIONS
function self = InputSection(className)
SOURCE CODE
classdef InputSection < Section
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        schedPolicy;
        inputJobClasses;
    end
    methods(Hidden)
        %Constructor
        function self = InputSection(className)
            self@Section(className);
        end
    end
end