Description of LogTunnel
Home > src > lang > LogTunnel.m
LogTunnel
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
LogTunnel
ServiceSection
This function is called by:
LogTunnel
Logger
SUBFUNCTIONS
function self = LogTunnel()
SOURCE CODE
classdef LogTunnel < ServiceSection
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
properties
    end
    methods
        %Constructor
        function self = LogTunnel()
            self = self@ServiceSection('LogTunnel');
            self.numberOfServers = 1;
            self.serviceProcess = {};
        end
    end
end