Description of NetworkElement
Home > src > lang > NetworkElement.m
NetworkElement
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Element
NetworkElement
This function is called by:
Chain
ItemClass
ItemSet
JobClass
NetworkElement
Node
Section
SUBFUNCTIONS
function self = NetworkElement(name)
SOURCE CODE
classdef NetworkElement < Element
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    methods
        %Constructor
        function self = NetworkElement(name)
            self@Element(name);
        end
    end
end