Description of OutputSection
Home > src > lang > OutputSection.m
OutputSection
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
OutputSection
Section
This function is called by:
Dispatcher
Forker
OutputSection
SUBFUNCTIONS
function self = OutputSection(className)
SOURCE CODE
classdef OutputSection < Section
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        outputStrategy;
    end
    methods(Hidden)
        %Constructor
        function self = OutputSection(className)
            self@Section(className);
        end
    end
end