Description of QueueingStation
Home > src > lang > QueueingStation.m
QueueingStation
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Queue
QueueingStation
This function is called by:
QueueingStation
SUBFUNCTIONS
function self = QueueingStation(model, name, schedStrategy)
SOURCE CODE
classdef QueueingStation < Queue
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    methods
        %Constructor
        function self = QueueingStation(model, name, schedStrategy)
            self = self@Queue(model, name, schedStrategy);
        end
    end
end