Description of Section
Home > src > lang > Section.m
Section
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
NetworkElement
Section
This function is called by:
InputSection
Joiner
OutputSection
Section
ServiceSection
Sink
SUBFUNCTIONS
function self = Section(className)
SOURCE CODE
classdef Section < NetworkElement
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        className;
    end
    methods(Hidden)
        %Constructor
        function self = Section(className)
            self@NetworkElement('Section');
            self.className = className;
        end
    end
end