Description of ServiceTunnel
Home > src > lang > ServiceTunnel.m
ServiceTunnel
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ServiceSection
ServiceTunnel
This function is called by:
Fork
Join
Router
ServiceTunnel
Source
SUBFUNCTIONS
function self = ServiceTunnel()
SOURCE CODE
classdef ServiceTunnel < ServiceSection
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    methods
        %Constructor
        function self = ServiceTunnel()
            self = self@ServiceSection('ServiceTunnel');
            self.numberOfServers = 1;
            self.serviceProcess = {};
        end
    end
end