Description of ServiceSection
Home > src > lang > ServiceSection.m
ServiceSection
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Section
ServiceSection
This function is called by:
CacheServer
ClassSwitcher
InfiniteServer
LogTunnel
Server
ServiceSection
ServiceTunnel
SharedServer
SUBFUNCTIONS
function self = ServiceSection(className)
SOURCE CODE
classdef ServiceSection < Section
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        numberOfServers;
        serviceProcess;
    end
    methods(Hidden)
        %Constructor
        function self = ServiceSection(className)
            self@Section(className);
        end
    end
end