Description of StatelessClassSwitcher
Home > src > lang > StatelessClassSwitcher.m
StatelessClassSwitcher
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ClassSwitcher
StatelessClassSwitcher
This function is called by:
ClassSwitch
StatelessClassSwitcher
SUBFUNCTIONS
function self = StatelessClassSwitcher(classes, csMatrix)
SOURCE CODE
classdef StatelessClassSwitcher < ClassSwitcher
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    methods
        %Constructor
        function self = StatelessClassSwitcher(classes, csMatrix)
            self = self@ClassSwitcher(classes, 'StatelessClassSwitcher');
            % this is slower than indexing the matrix, but it is a small
            % matrix anyway
            self.csFun = @(r,s,state,statep) csMatrix(r,s); % state parameter if present is ignored
        end
    end
end