Description of StatefulNode
Home > src > lang > StatefulNode.m
StatefulNode
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Node
StatefulNode
This function is called by:
Cache
StatefulNode
Station
SUBFUNCTIONS
function self = StatefulNode(name)
function prior = getStatePrior(self)
function self = setStatePrior(self, prior)
function self = setState(self, state)
function state = getState(self)
function self = setStateSpace(self, space)
function self = resetStateSpace(self)
SOURCE CODE
classdef StatefulNode < Node
    % Copyright (c) 2012-2019, Imperial College London
    % All rights reserved.
    properties
        state;
        statePrior;
        space;
    end
    methods(Hidden)
        %Constructor
        function self = StatefulNode(name)
            self@Node(name);
            self.statePrior = [];
            self.state = [];
            self.space = {};
        end
        function prior = getStatePrior(self)
            % prior(j) = probability that the initial state is state(j)
            prior = self.statePrior;
        end
        function self = setStatePrior(self, prior)
            % the prior is marginalized on the station state and thus
            % assumed independent of the priors for other stations
            self.statePrior = prior(:); % we do not normalize to allow the user to manually run a model for each point of an external prior
            if size(self.statePrior,1) ~= size(self.state,1)
                error('The prior probability vector must have the same rows of the station state vector.');
            end
        end
        function self = setState(self, state)
            % state can be stacked in a matrix of states, a state space
            self.state = state;
            if size(self.statePrior,1) ~= size(self.state,1)
                %self.setStatePrior(ones(size(state,1),1)/size(state,1));
                initPrior = zeros(size(state,1),1); initPrior(1) = 1;
                self.setStatePrior(initPrior);
            end
        end
        function state = getState(self)
            state = self.state;
        end
        function self = setStateSpace(self, space)
            self.space = space;
            %            mState.getHash = memoize(@(x) self.State.getHash(x));
        end
        function self = resetStateSpace(self)
            self.space = {};
        end
    end
end