Description of LayeredNetwork
Home > src > lang > @LayeredNetwork > LayeredNetwork.m
LayeredNetwork
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
LayeredNetwork
findEdgeIndex Copyright (c) 2012-2019, Imperial College London
findEntryOfActivity Copyright (c) 2012-2019, Imperial College London
generateGraph Copyright (c) 2012-2019, Imperial College London
getGraph Copyright (c) 2012-2019, Imperial College London
getGraphLayers Copyright (c) 2012-2019, Imperial College London
getNodeFullName Copyright (c) 2012-2019, Imperial College London
getNodeIndex Copyright (c) 2012-2019, Imperial College London
getNodeIndexInTaskGraph Copyright (c) 2012-2019, Imperial College London
getNodeName Copyright (c) 2012-2019, Imperial College London
getNodeObject Copyright (c) 2012-2019, Imperial College London
getNodeProcessor Copyright (c) 2012-2019, Imperial College London
getNodeTask Copyright (c) 2012-2019, Imperial College London
getNodeType Copyright (c) 2012-2019, Imperial College London
initDefault Copyright (c) 2012-2019, Imperial College London
isValid Copyright (c) 2012-2019, Imperial College London
listActivitiesOfEntry Copyright (c) 2012-2019, Imperial College London
listEntriesOfTask Copyright (c) 2012-2019, Imperial College London
parseXML Copyright (c) 2012-2019, Imperial College London
plot Copyright (c) 2012-2019, Imperial College London
setGraph Copyright (c) 2012-2019, Imperial College London
update Copyright (c) 2012-2019, Imperial College London
updateEnsemble Copyright (c) 2012-2019, Imperial College London
updateParam Copyright (c) 2012-2019, Imperial College London
writeSRVN Copyright (c) 2012-2019, Imperial College London
writeXML Copyright (c) 2012-2019, Imperial College London
This function is called by:
LayeredNetwork
parseXML Copyright (c) 2012-2019, Imperial College London
SUBFUNCTIONS
function self = LayeredNetwork(name, filename)
function self = init(self)
function E = getNumberOfLayers(self)
function E = getNumberOfModels(self)
function layers = getLayers(self)
function self = setUsedFeatures(self,e,className)
function self = initUsedFeatures(self)
function usedFeatures = getUsedLangFeatures(self)
SOURCE CODE
classdef LayeredNetwork < Model & Ensemble
% Copyright (c) 2012-2019, Imperial College London
% All rights reserved.
    properties
        objects = struct();    % cell arrays of objects
        processors = cell(0,4);      % list of processors
        lqnGraph; % digraph representation of all dependencies
        taskGraph; % digraph representation of task dependencies
        layerGraph;
        clientTask;
        nodeNames;
        nodeDep; % (i,1) = procId, (i,2) = taskId, (i,3) = entryId, NaN is n/a
        endNodes;
        nodeMult;
        edgeWeight;
        param; % Avg performance metrics are input parameters in LQNs
        syncCall = cell(1,0);
        asyncCall = cell(1,0);
        isCall = cell(1,0);
        syncSource = cell(1,0);
        asyncSource = cell(1,0);
        syncDest = cell(1,0);
        asyncDest = cell(1,0);
        chains = cell(1,0);
        serverName = cell(1,0);
        usedFeatures; % cell with structures of booleans listing the used classes
        % it must be accessed via getUsedLangFeatures
    end
    methods
        %public methods, including constructor
        % constructor
        function self = LayeredNetwork(name, filename)
            self@Ensemble({})
            if ~exist('name','var')
                [~,name]=fileparts(tempname);
            end
            self = self@Model(name);
            self.lqnGraph = [];
            self.taskGraph = [];
            self.ensemble = {};
            self.objects.processors = {};
            self.objects.tasks = {};
            self.objects.entries = {};
            self.objects.activities = {};
            self.param.Nodes.RespT = [];
            self.param.Nodes.Tput = [];
            self.param.Nodes.Util = [];
            self.param.Edges.RespT = [];
            self.param.Edges.Tput = [];
            if exist('filename','var')
                self = LayeredNetwork.parseXML(filename, false);
                self.init;
            end
        end
        function self = init(self)
            self.generateGraph;
            self.initDefault;
            self.param.Nodes.RespT = [];
            self.param.Nodes.Tput = [];
            self.param.Nodes.Util = [];
            self.param.Nodes.QLen = [];
            self.param.Edges.RespT = [];
            self.param.Edges.Tput = [];
            self.param.Edges.QLen = [];
        end
        ensemble = updateEnsemble(self, isBuild, deepUpdate)
        self = generateGraph(self);
        [lqnGraph,taskGraph] = getGraph(self)
        self = setGraph(self,lqnGraph,taskGraph)
        [subgraphs, levels] = getGraphLayers(self, lqnGraph, taskGraph)
        bool = isValid(self)
        self = update(self)
        self = updateParam(self, AvgTable)
        self = initDefault(self)
        plot(self)
    end
    methods
        % these methods access the graph functions
        [entry, entryFullName] = findEntryOfActivity(self,activity)
        idx = findEdgeIndex(self,source,dest)
        entries = listEntriesOfTask(self,task);
        acts = listActivitiesOfEntry(self,entry);
        % these methods extract node data from lqnGraph.Nodes
        idx = getNodeIndex(self,node) %converted
        idx = getNodeIndexInTaskGraph(self,node)
        fullName = getNodeFullName(self,node)
        name = getNodeName(self,node,useNode)
        obj = getNodeObject(self,node)
        proc = getNodeProcessor(self,node)
        task = getNodeTask(self,nodeNameOrIdx)
        type = getNodeType(self,nodeNameOrIdx)
        writeSRVN(self,filename);
        writeXML(self,filename);
    end
    methods
        function E = getNumberOfLayers(self)
            E = self.getNumberOfModels();
        end
        function E = getNumberOfModels(self)
            if isempty(self.ensemble)
                self.ensemble = self.getEnsemble();
            end
            E = length(self.ensemble);
        end
        function layers = getLayers(self)
            layers = self.getEnsemble();
        end
        % setUsedFeatures : records that a certain language feature has been used
        function self = setUsedFeatures(self,e,className)
            self.usedFeatures{e}.setTrue(className);
        end
        function self = initUsedFeatures(self)
            for e=1:self.getNumberOfModels()
                self.usedFeatures{e} = SolverFeatureSet;
            end
        end
        function usedFeatures = getUsedLangFeatures(self)
            E = self.getNumberOfLayers();
            usedFeatures = cell(1,E);
            for e=1:E
                usedFeatures{e} = self.ensemble{e}.getUsedLangFeatures;
            end
            self.usedFeatures = usedFeatures;
        end
    end
    methods (Static)
        myLN = parseXML(filename, verbose)
    end
end