Description of ContinuousDistrib
Home > src > lang > distributions > ContinuousDistrib.m
ContinuousDistrib
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ContinuousDistrib
Distrib
This function is called by:
ContinuousDistrib
Gamma
Pareto
PhaseType
Uniform
SUBFUNCTIONS
function self = ContinuousDistrib(name, numParam, support)
SOURCE CODE
classdef ContinuousDistrib < Distrib
    % Copyright (c) 2018-Present, Imperial College London
    % All rights reserved.
    properties
    end
    methods (Hidden)
        %Constructor
        function self = ContinuousDistrib(name, numParam, support)
            self = self@Distrib(name,numParam,support);
        end
    end
end