Description of Immediate
Home > src > lang > distributions > Immediate.m
Immediate
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Distrib
Immediate
This function is called by:
Immediate
SUBFUNCTIONS
function self = Immediate()
function bool = isDisabled(self)
function X = sample(self)
function ex = getMean(self)
function SCV = getSCV(self)
function Ft = evalCDF(self,t)
SOURCE CODE
classdef Immediate < Distrib
    % Copyright (c) 2018-Present, Imperial College London
    % All rights reserved.
    methods (Hidden)
        %Constructor
        function self = Immediate()
            self@Distrib('Immediate', 0,[0,0]);
        end
    end
    methods
        function bool = isDisabled(self)
            bool = false;
        end
        function X = sample(self)
            X = 0;
        end
        function ex = getMean(self)
            ex = 0;
        end
        function SCV = getSCV(self)
            SCV = 0;
        end
        function Ft = evalCDF(self,t)
            Ft = 1;
        end
    end
end